-- Devir cloud sync infrastructure for BisonTCG.
-- Idempotent reference/bootstrap SQL. Contains no credentials.
-- Runtime secrets (worker token, Spree key, Devir session) are injected separately.

create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net;

create table if not exists public.devir_sync_config (
  id text primary key,
  enabled boolean not null default false,
  base_url text not null default 'https://b2bdevir.es',
  spree_api_url text not null default 'https://bisontcg.spree.sh',
  spree_admin_api_key text,
  session_state jsonb,
  worker_url text not null default 'https://ikglqbjlbkbaronbiryl.supabase.co/functions/v1/devir-sync',
  worker_token_hash text,
  interval_hours integer not null default 6 check (interval_hours between 1 and 168),
  batch_size integer not null default 4 check (batch_size between 1 and 20),
  max_pages integer not null default 200 check (max_pages between 1 and 500),
  phase text not null default 'idle' check (phase in ('idle','categories','products','error')),
  active_cycle_id uuid,
  next_due_at timestamptz not null default now(),
  lock_until timestamptz,
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);

create table if not exists public.devir_sync_cycles (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'running' check (status in ('running','success','error')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  category_count integer not null default 0,
  product_count integer not null default 0,
  processed_count integer not null default 0,
  error_count integer not null default 0,
  stats jsonb not null default '{}'::jsonb,
  error text
);

create table if not exists public.devir_sync_jobs (
  id bigint generated by default as identity primary key,
  cycle_id uuid not null references public.devir_sync_cycles(id) on delete cascade,
  kind text not null check (kind in ('category','product')),
  url text not null,
  page integer not null default 1 check (page > 0),
  status text not null default 'pending' check (status in ('pending','processing','done','error')),
  attempts integer not null default 0,
  payload jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cycle_id, kind, url, page)
);

create index if not exists devir_sync_jobs_cycle_status_idx
  on public.devir_sync_jobs (cycle_id, kind, status, id);

create table if not exists public.devir_sync_catalog (
  supplier_sku text primary key,
  source_url text not null,
  name text not null,
  snapshot jsonb not null,
  image_urls jsonb not null default '[]'::jsonb,
  image_signature text,
  spree_product_id text,
  spree_variant_id text,
  images_managed boolean not null default true,
  last_seen_cycle_id uuid references public.devir_sync_cycles(id) on delete set null,
  last_seen_at timestamptz not null default now(),
  last_synced_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);

create index if not exists devir_sync_catalog_cycle_idx
  on public.devir_sync_catalog(last_seen_cycle_id);

alter table public.devir_sync_config enable row level security;
alter table public.devir_sync_cycles enable row level security;
alter table public.devir_sync_jobs enable row level security;
alter table public.devir_sync_catalog enable row level security;

revoke all on table public.devir_sync_config from anon, authenticated;
revoke all on table public.devir_sync_cycles from anon, authenticated;
revoke all on table public.devir_sync_jobs from anon, authenticated;
revoke all on table public.devir_sync_catalog from anon, authenticated;

drop policy if exists devir_sync_config_deny_clients on public.devir_sync_config;
create policy devir_sync_config_deny_clients
  on public.devir_sync_config for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists devir_sync_cycles_deny_clients on public.devir_sync_cycles;
create policy devir_sync_cycles_deny_clients
  on public.devir_sync_cycles for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists devir_sync_jobs_deny_clients on public.devir_sync_jobs;
create policy devir_sync_jobs_deny_clients
  on public.devir_sync_jobs for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists devir_sync_catalog_deny_clients on public.devir_sync_catalog;
create policy devir_sync_catalog_deny_clients
  on public.devir_sync_catalog for all
  to anon, authenticated
  using (false)
  with check (false);

grant select, insert, update, delete on table public.devir_sync_config to service_role;
grant select, insert, update, delete on table public.devir_sync_cycles to service_role;
grant select, insert, update, delete on table public.devir_sync_jobs to service_role;
grant select, insert, update, delete on table public.devir_sync_catalog to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.devir_sync_acquire_lock(p_seconds integer default 55)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_acquired boolean := false;
begin
  update public.devir_sync_config
  set lock_until = now() + make_interval(secs => greatest(10, least(p_seconds, 240))),
      last_attempt_at = now(),
      updated_at = now()
  where id = 'primary'
    and (lock_until is null or lock_until < now())
  returning true into v_acquired;

  return coalesce(v_acquired, false);
end;
$$;

create or replace function public.devir_sync_release_lock()
returns void
language sql
security definer
set search_path = ''
as $$
  update public.devir_sync_config
  set lock_until = null, updated_at = now()
  where id = 'primary';
$$;

revoke all on function public.devir_sync_acquire_lock(integer) from public, anon, authenticated;
revoke all on function public.devir_sync_release_lock() from public, anon, authenticated;
grant execute on function public.devir_sync_acquire_lock(integer) to service_role;
grant execute on function public.devir_sync_release_lock() to service_role;

do $$
declare
  v_token text;
begin
  select decrypted_secret
  into v_token
  from vault.decrypted_secrets
  where name = 'devir_sync_worker_token'
  limit 1;

  if v_token is null then
    v_token := encode(extensions.gen_random_bytes(32), 'hex');
    perform vault.create_secret(
      v_token,
      'devir_sync_worker_token',
      'Bearer token used only by Supabase Cron to invoke the Devir sync worker',
      null
    );
  end if;

  insert into public.devir_sync_config (
    id, worker_token_hash, worker_url, enabled, next_due_at
  )
  values (
    'primary',
    encode(extensions.digest(v_token, 'sha256'), 'hex'),
    'https://ikglqbjlbkbaronbiryl.supabase.co/functions/v1/devir-sync',
    false,
    now()
  )
  on conflict (id) do update
  set worker_token_hash = excluded.worker_token_hash,
      worker_url = excluded.worker_url,
      updated_at = now();
end;
$$;

select cron.unschedule(jobid)
from cron.job
where jobname = 'devir-cloud-sync-tick';

select cron.schedule(
  'devir-cloud-sync-tick',
  '* * * * *',
  $cron$
  select net.http_post(
    url := (select worker_url from public.devir_sync_config where id = 'primary'),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-devir-worker-token',
      (select decrypted_secret from vault.decrypted_secrets where name = 'devir_sync_worker_token' limit 1)
    ),
    body := jsonb_build_object('source', 'supabase-cron', 'at', now()),
    timeout_milliseconds := 120000
  );
  $cron$
);
